name: deepseek-phi
channels:
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers>=4.39.0
      - peft>=0.8.2
      - accelerate
      - bitsandbytes
      - datasets
      - scikit-learn
      - nltk
      - huggingface_hub
      - numpy
      - scipy
